version: '3'
services:
  web-app:
    build: 
      context: ./app
      target: dev
    command: npx webpack-dev-server
    ports:
      - 8080:8080
    volumes:
      - ./app:/srv/todo/app
      # - ./app/:/usr/share/nginx/html
    depends_on:
      - api
    environment:
      DOMAIN_URL: ${DOMAIN_URL}
      APP_PORT: ${APP_PORT}
      API_PORT: ${API_PORT}


  api:
    build: ./api
    ports:
      - 8000:80
    volumes:
      - ./api/public:/var/www/html
      - ./api/src:/var/www/src
      - ./api/vendor:/var/www/vendor
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PMA_HOST: ${PMA_HOST}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DOMAIN_URL: ${DOMAIN_URL}
      APP_PORT: ${APP_PORT}
      API_PORT: ${API_PORT}
    depends_on:
      - db
    restart: unless-stopped

  composer:
    restart: 'no'
    image: composer/composer
    command: install
    volumes:
      - ./api:/app
  
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - db

volumes:
  app_node_modules:
  db-data: